.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OCCTL" "8" "April 2018" "" ""
.
.SH "NAME"
\fBocctl\fR \- OpenConnect VPN server control tool
.
.SH "SYNOPSIS"
\fBocctl\fR [\'COMMAND\']
.
.SH "DESCRIPTION"
This a control tool that can be used to send commands to ocserv\. When called without any arguments the tool can be used interactively, where each command is entered on a command prompt; alternatively the tool can be called with the command specified as parameter\. In the latter case the tool\'s exit code will reflect the successful execution of the command\.
.
.SH "OPTIONS"
.
.TP
\fB\-s, \-\-socket\-file\fR=\fIFILE\fR
Specify the server\'s occtl socket file\. This option is only needed if you have multiple servers\.
.
.TP
\fB\-j, \-\-json\fR
Output will be JSON formatted\. This option can only be used with non\-interactive output, e\.g\., \'occtl \-\-json show users\'\.
.
.TP
\fB\-n, \-\-no\-pager\fR
No pager will be used over output data\.
.
.TP
\fB\-\-debug\fR
Provide more verbose information in some commands\.
.
.TP
\fB\-h, \-\-help\fR
Display usage information and exit\.
.
.TP
\fB\-v, \-\-version\fR
Output version of program and exit\.
.
.SH "IMPLEMENTATION NOTES"
This tool uses unix domain sockets to connect to ocserv\.
.
.SH "EXAMPLES"
The tool can be run interactively when run with no arguments\. When arguments are given they are interpreted as commands\. For example:
.
.IP "" 4
.
.nf

$ occtl show users
.
.fi
.
.IP "" 0
.
.P
Any command line arguments to be used as options must precede the command (if any), as shown below\.
.
.IP "" 4
.
.nf

$ occtl \-\-json show users
.
.fi
.
.IP "" 0
.
.SH "Exit status"
.
.TP
\fB0\fR
Successful program execution\.
.
.TP
\fB1\fR
The operation failed or the command syntax was not valid\.
.
.SH "SEE ALSO"
ocserv(8), ocpasswd(8)
.
.SH "COPYRIGHT"
Copyright (C) 2013\-2017 Nikos Mavrogiannopoulos and others, all rights reserved\. This program is released under the terms of the GNU General Public License, version 2\.
.
.SH "AUTHORS"
Written by Nikos Mavrogiannopoulos\. Many people have contributed to it\.
