.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "OCPASSWD" "8" "April 2018" "" ""
.
.SH "NAME"
\fBocpasswd\fR \- OpenConnect server password utility
.
.SH "SYNOPSIS"
\fBocpasswd\fR [\-\-option\-name[=value]] [\'username\']
.
.SH "DESCRIPTION"
This program is openconnect password (ocpasswd) utility\. It allows the generation and handling of a \'plain\' password file used by ocserv\.
.
.SH "OPTIONS"
.
.TP
\fB\-c, \-\-passwd\fR=\fIFILE\fR:
Specify the password file to use\. Only useful when not using the default location\.
.
.TP
\fB\-g, \-\-group\fR:
Specify the user\'s group name\.
.
.TP
\fB\-d, \-\-delete\fR:
Deletes the specified user from the password file\.
.
.TP
\fB\-l, \-\-lock\fR:
Prevents the specified user from logging in by locking its password\.
.
.TP
\fB\-u, \-\-unlock\fR:
Re\-enables login for the specified user by unlocking its password\.
.
.TP
\fB\-h, \-\-help\fR:
Display usage information and exit\.
.
.TP
\fB\-v, \-\-version\fR:
Output version of program and exit\.
.
.SH "FILES"
The password format of ocpasswd is as follows\.
.
.IP "" 4
.
.nf

username:groupname:encoded\-password
.
.fi
.
.IP "" 0
.
.P
The crypt(3) encoding is used for the encoded\-password\.
.
.SH "EXAMPLES"
.
.SS "Adding a user"
.
.nf

$ ocpasswd \-c ocpasswd my_username
.
.fi
.
.SS "Locking a user"
.
.nf

$ ocpasswd \-c ocpasswd \-l my_username
.
.fi
.
.SS "Unlocking a user"
.
.nf

$ ocpasswd \-c ocpasswd \-u my_username
.
.fi
.
.SH "Exit status"
.
.TP
\fB0\fR
Successful program execution\.
.
.TP
\fB1\fR
The operation failed or the command syntax was not valid\.
.
.SH "SEE ALSO"
ocserv(8), occtl(8)
.
.SH "COPYRIGHT"
Copyright (C) 2013\-2017 Nikos Mavrogiannopoulos and others, all rights reserved\. This program is released under the terms of the GNU General Public License, version 2\.
.
.SH "AUTHORS"
Written by Nikos Mavrogiannopoulos\. Many people have contributed to it\.
